### DISCUSSION TITLE
WebDAV Server for Centralized Backup and Sync Across Laptops

### DISCUSSION THREAD

**Discussion by IliaOzhmegov** [super-productivity/super-productivity#3851] [Q&A] [answered]
Context:
I'm setting up a WebDAV server to act as a centralized location for syncing and backing up files across multiple laptops. I want to use this WebDAV server while Super Productivity is run locally on one of my laptops, but I'm encountering issues during the setup process.

Setup:

- Access URL: `http://192.168.178.24:8080` (running on a Raspberry Pi in my local network).
- docker-compose.yaml:
```
services:
  webdav:
    image: hacdias/webdav:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
```
- webdav.yaml:
```
address: 0.0.0.0
port: 8080

prefix: /
permissions: CRUD

users:
  - username: ilia
    password: password
    directory: /data/ilia

```

What Works:

- I can access the WebDAV server via curl:
`curl -u ilia:password -T test.json http://192.168.178.24:8080`
This successfully creates a file in the data/ilia directory on the server.
- Directory listings and file uploads work as expected with curl.

The Problem:
When trying to connect Super Productivity to the WebDAV server:
1. Base URL: `http://192.168.178.24:8080` (also tried `http://192.168.178.24:8080/webdav`, `http://192.168.178.24:8080/data/ilia`)
2. Sync Folder Path: `super-productivity-backup.json`
3. Username: `ilia`
4. Password: `password`

Super Productivity returns an error:
`Error: Unknown Upload Error (Settings correct?): Error: Invalid response: 409 Conflict`

<img width="743" alt="Screenshot 2025-01-09 at 02 59 48" src="https://github.com/user-attachments/assets/247d881c-b421-4f89-b8be-ec0235e236e7" />

My Goal:
To have a central WebDAV server accessible to multiple laptops for file synchronization, starting with Super Productivity.

Questions:
1. What is the correct WebDAV URL structure for Super Productivity? Should the Base URL include the folder (/data/ilia), or is that specified in the Sync Folder Path?
2. Could the 409 Conflict error be related to file-locking, permissions, or another WebDAV-specific configuration?
3. Are there specific settings or logs in Super Productivity or the WebDAV server to debug this issue further?
4. Are there known compatibility issues between Super Productivity and certain WebDAV servers (e.g., hacdias/webdav)?
5. Does the `WEBDAV_BACKEND` variable in the `hacdias/webdav` Docker container play any role here? If so:
    - What values are supported for this variable?
    - Does it impact compatibility with Super Productivity, and should it be configured to a specific backend?

**Comment by IliaOzhmegov** [comment]
I've decided to step back and try to run that in locally, 2 containers, exactly the same as was written in the readme of the project. Well it fails...

However, when I search thru PRs regarding webdav I found this: https://github.com/johannesjo/super-productivity/pull/3534

TLDR: 

- add folder `super-productivity` in your local folder in my case it was `data/ilia`. 
- make sure Sync Folder Path is also `super-productivity` I used to have `super-productivity-backup.json` -- no idea why thou

**Comment by IliaOzhmegov** [comment]
just for the sake of not losing the progress to make it work at least with docker-compose, let me document it here.

File structure:
```
❯ tree
.
├── data
│   └── ilia
│       └── super-productivity
│           ├── ARCHIVE.json
│           └── MAIN.json
├── docker-compose.yml
└── webdav.yaml

4 directories, 4 files
```
docker-compose.yml:
```
services:
  sp:
    image: johannesjo/super-productivity:latest
    ports:
      - 80:80
    environment:
      - WEBDAV_BACKEND=http://webdav # Optional

  # Optional: WebDAV backend server
  # (used with the WEBDAV_BACKEND environment variable)
  webdav:
    image: hacdias/webdav:latest
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
```

webdav.yaml:
```
address: 0.0.0.0
port: 80

prefix: /
permissions: CRUD

users:
  - username: ilia
    password: iliapassword
    directory: /data/ilia
```

Since it's not very intuitive let also show my
settings in super-productivity:
<img width="838" alt="Screenshot 2025-01-16 at 06 59 12" src="https://github.com/user-attachments/assets/62440410-7c04-4eb2-b951-997435154495" />

**Comment by tune007** [comment]
Hi Ilia , for which provider are you trying to setup webdav e.g. NextCloud/Seafile etc. because I think the base URL will look different for each. I think 409 error means the library you are trying to access does not exist. Also the part where you are specifying the sync folder path refers to your library path not the actual json file so for instance if the library/folder name is SuperProd that should be what you specify in your basefolder path. By default SP will try to create it's own "folder" called super-productivity which if it does not exist on your webdav instance will give you the 409 error. Also if you are deploying a docker container you probably are using ngnix that you need to configure correctly for your webdav service. Hope I understood your question correctly :)

**Reply by IliaOzhmegov** [reply]
Hi @tune007,

Thank you for taking the time to respond. I’m not actually using Nextcloud or Seafile—rather, I’m running a Docker-based WebDAV server (specifically the `hacdias/webdav` image) alongside Super Productivity. The 409 error I’m seeing doesn’t appear to be due to a missing “library” in the sense of Nextcloud/Seafile libraries; instead, it seems related to how Super Productivity handles its sync folder path and tries to write files (like `MAIN.json` and `ARCHIVE.json`).

From what I’ve gathered:

1. Super Productivity will create or expect a folder (e.g. `/super-productivity`) on the WebDAV server and store multiple JSON files there.
2. If I mistakenly set a “Sync Folder Path” in Super Productivity to something that looks like a single file (e.g. `someFile.json`), SP attempts requests like `PUT /someFile.json/MAIN.json`, which the WebDAV server interprets as a directory path, causing the 409 or 405 errors.
3. I’m also using Nginx inside the Super Productivity container, but I’ve tried to keep that separate from the WebDAV instance.

So in my case, it’s not about Nextcloud/Seafile “libraries” specifically, but rather how the path is handled on the `hacdias/webdav` server. Thanks for suggesting the idea of a missing library/folder—turns out that logic still applies in the sense that I need to ensure the correct folder name is used for SP’s sync path, so the server sees a valid directory.

I appreciate your input and hope this clarifies my setup. If you have more thoughts on dealing with 409 conflicts in a basic Docker-based WebDAV environment, I’d love to hear them. Thanks again for helping me troubleshoot!

**Comment by IliaOzhmegov** [comment, marked as answer]
My solution for my raspberry pi (with access from within local network)

File structure:
```
.
├── data
│   └── ilia
│       └── super-productivity
│           ├── ARCHIVE.json
│           └── MAIN.json
├── docker-compose.yaml
└── webdav.yaml

```
Note: files `ARCHIVE.json` and `MAIN.json` were created in the result of synchronization. Folders `data/ilia/super-productivity` were created manually.


webdav.yaml:
```
address: 0.0.0.0
port: 80

prefix: /
permissions: CRUD

users:
  - username: ilia
    password: iliapassword
    directory: /data/ilia
```


docker-compose.yaml:
```
services:
  webdav:
    image: hacdias/webdav:latest
    ports:
      - "8080:80"
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
```
Note: I'm accessing webdav externally via port `8080`.

The configuration of Sync in SP that is running natively on my machine:
<img width="778" alt="Screenshot 2025-01-26 at 23 18 16" src="https://github.com/user-attachments/assets/c420b3ad-9f2f-4296-af6e-1a9d48f82bcf" />

Note: Raspberry pi's address in local network is `http://192.168.178.24`.

I also need to set up:
* https
* accessibility of my raspberry pi from external network
* port forwarding in my route
* leverage DDNS like duckdns to access my RP with a sensible domain name instead of ipv6, which I currently use

But all of these todos are outside of the scope of relevance for current discussion. But what is relevant is the way of syncing those files between different laptops, particularly when something goes wrong: personal laptop failed to sync with webdav due to some reason, and I need to continue to do something on a working laptop after. Apparently it's implied that when I start launching SP you pull remote files first, and when you are finishing work up push them on webdav to avoid some kind of conflict. But for that I'll check other discussions first or created a dedicated one if necessary.
